apiVersion: v1
kind: ConfigMap
metadata:
  name: django-app-config
  labels:
    app: django-app
data:
  DJANGO_DEBUG: {{ .Values.config.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.DJANGO_ALLOWED_HOSTS | quote }}